import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [
    'guide/intro',
    'guide/app-source',
    {
      type: 'category',
      label: '푸시 알림',
      link: {
        type: 'generated-index',
        title: '푸시 알림 (Push Notification)',
        slug: '/guide/push',
      },
      items: [
        'guide/push/push-token',
        'guide/push/personal-push',
        'guide/push/topic-push',
        'guide/push/all-push',
        'guide/push/local-push',
      ],
    },
    {
      type: 'category',
      label: '딥링크',
      link: {
        type: 'generated-index',
        title: '딥링크 (Deep Link)',
        slug: '/guide/deep-link',
      },
      items: [
        'guide/deep-link/intro',
        'guide/deep-link/uri-scheme',
        'guide/deep-link/intent-scheme',
        'guide/deep-link/universal-link',
        'guide/deep-link/app-link',
        'guide/deep-link/nachocode-link',
      ],
    },
    'guide/iap',
    {
      type: 'category',
      label: '웹훅',
      link: {
        type: 'generated-index',
        title: '웹훅 (Webhook)',
        slug: '/guide/webhook',
      },
      items: [
        'guide/webhook/overview',
        {
          type: 'category',
          label: '인앱 결제',
          link: {
            type: 'generated-index',
            title: '인앱 결제',
            slug: '/guide/webhook/iap',
          },
          items: ['guide/webhook/iap/purchase', 'guide/webhook/iap/refund'],
        },
        {
          type: 'category',
          label: '개인화 푸시',
          link: {
            type: 'generated-index',
            title: '개인화 푸시',
            slug: '/guide/webhook/personal-push',
          },
          items: ['guide/webhook/personal-push/unavailable-users'],
        },
      ],
    },
    {
      type: 'category',
      label: 'User Agent',
      link: {
        type: 'generated-index',
        title: '유저에이전트 (User Agent)',
        slug: '/guide/user-agent',
      },
      items: [
        'guide/user-agent/user-agent-definition',
        'guide/user-agent/user-agent-configuration',
      ],
    },
    {
      type: 'category',
      label: '샌드박스 앱',
      link: {
        type: 'generated-index',
        title: '샌드박스 앱',
        slug: '/guide/sandbox',
      },
      items: [
        'guide/sandbox/sandbox-overview',
        'guide/sandbox/sandbox-inspector',
        'guide/sandbox/sandbox-debugging',
      ],
    },
    'guide/check-store-id',
  ],
  api: [
    'api/intro',
    {
      type: 'category',
      label: '푸시 알림',
      link: {
        type: 'generated-index',
        title: '푸시 알림 (Push Notification)',
        slug: '/api/push',
      },
      items: [
        'api/push/push-token.endpoints',
        'api/push/personal-push.endpoints',
        'api/push/topic-push.endpoints',
        'api/push/all-push.endpoints',
      ],
    },
  ],
  sdk: [
    'sdk/intro',
    'sdk/getting-started',
    'sdk/typescript-support',
    'sdk/react-support',
    {
      type: 'category',
      label: '네임스페이스',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '네임스페이스',
        slug: '/sdk/namespaces',
      },
      items: [
        'sdk/namespaces/app',
        'sdk/namespaces/authentication',
        'sdk/namespaces/backkey',
        'sdk/namespaces/browser',
        'sdk/namespaces/clipboard',
        'sdk/namespaces/device',
        'sdk/namespaces/env',
        'sdk/namespaces/event',
        'sdk/namespaces/iap',
        'sdk/namespaces/loading',
        'sdk/namespaces/location',
        'sdk/namespaces/navigation',
        'sdk/namespaces/permission',
        'sdk/namespaces/preference',
        'sdk/namespaces/push',
        'sdk/namespaces/refresh',
        'sdk/namespaces/scanner',
        'sdk/namespaces/setting',
        'sdk/namespaces/share',
        'sdk/namespaces/store',
        'sdk/namespaces/tabbar',
        'sdk/namespaces/vibration',
      ],
    },
    {
      type: 'category',
      label: '네임스페이스 (외부연동)',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '네임스페이스 (외부연동)',
        slug: '/sdk/integrations',
      },
      items: [
        {
          type: 'category',
          label: '애플 (apple)',
          link: {
            type: 'generated-index',
            title: '애플 (apple)',
            slug: 'sdk/integrations/apple',
          },
          items: [
            'sdk/integrations/apple/integrate',
            'sdk/integrations/apple/reference',
          ],
        },
        {
          type: 'category',
          label: '앱스플라이어 (appsflyer)',
          link: {
            type: 'generated-index',
            title: '앱스플라이어 (appsflyer)',
            slug: '/sdk/integrations/appsflyer',
          },
          items: [
            'sdk/integrations/appsflyer/integrate',
            'sdk/integrations/appsflyer/reference',
          ],
        },
        {
          type: 'category',
          label: '페이스북 (facebook)',
          link: {
            type: 'generated-index',
            title: '페이스북 (facebook)',
            slug: '/sdk/integrations/facebook',
          },
          items: [
            'sdk/integrations/facebook/integrate',
            'sdk/integrations/facebook/reference',
          ],
        },
        {
          type: 'category',
          label: '구글 (google)',
          link: {
            type: 'generated-index',
            title: '구글 (google)',
            slug: '/sdk/integrations/google',
          },
          items: [
            'sdk/integrations/google/integrate',
            'sdk/integrations/google/reference',
          ],
        },
        {
          type: 'category',
          label: '카카오 (kakao)',
          link: {
            type: 'generated-index',
            title: '카카오 (kakao)',
            slug: '/sdk/integrations/kakao',
          },
          items: [
            'sdk/integrations/kakao/integrate',
            'sdk/integrations/kakao/reference',
          ],
        },
      ],
    },
  ],
  releases: [
    {
      type: 'category',
      label: 'SDK',
      link: {
        type: 'generated-index',
        title: 'nachocode Client SDK 릴리즈노트',
        image: '/img/docs/releases/release_note_sdk.png',
        slug: 'releases/v1/sdk',
      },
      items: [
        'releases/v1/sdk/intro',
        'releases/v1/sdk/release-v-1-8-0',
        'releases/v1/sdk/release-v-1-7-0',
        'releases/v1/sdk/release-v-1-6-3',
        'releases/v1/sdk/release-v-1-6-2',
        'releases/v1/sdk/release-v-1-6-1',
        'releases/v1/sdk/release-v-1-6-0',
        'releases/v1/sdk/release-v-1-5-0',
        'releases/v1/sdk/release-v-1-4-2',
        'releases/v1/sdk/release-v-1-4-1',
        'releases/v1/sdk/release-v-1-4-0',
        'releases/v1/sdk/release-v-1-3-0',
        'releases/v1/sdk/release-v-1-2-0',
        'releases/v1/sdk/release-v-1-1-0',
        'releases/v1/sdk/release-v-1-0-3',
        'releases/v1/sdk/release-v-1-0-2',
        'releases/v1/sdk/release-v-1-0-0',
      ],
    },
    {
      type: 'category',
      label: 'App Source',
      link: {
        type: 'generated-index',
        title: '앱소스 (App Source)',
        slug: 'releases/v1/app-source',
      },
      items: [
        {
          type: 'category',
          label: 'Android',
          link: {
            type: 'generated-index',
            title: 'Android App Source 릴리즈노트',
            image: '/img/docs/releases/release_note_android.png',
            slug: 'releases/v1/app-source/android',
          },
          items: [
            'releases/v1/app-source/android/intro',
            'releases/v1/app-source/android/release-v-1-8-6',
            'releases/v1/app-source/android/release-v-1-8-5',
            'releases/v1/app-source/android/release-v-1-8-4',
            'releases/v1/app-source/android/release-v-1-8-3',
            'releases/v1/app-source/android/release-v-1-8-2',
            'releases/v1/app-source/android/release-v-1-8-1',
            'releases/v1/app-source/android/release-v-1-8-0',
            'releases/v1/app-source/android/release-v-1-7-1',
            'releases/v1/app-source/android/release-v-1-7-0',
            'releases/v1/app-source/android/release-v-1-6-11',
            'releases/v1/app-source/android/release-v-1-6-10',
            'releases/v1/app-source/android/release-v-1-6-9',
            'releases/v1/app-source/android/release-v-1-6-8',
            'releases/v1/app-source/android/release-v-1-6-7',
            'releases/v1/app-source/android/release-v-1-6-6',
            'releases/v1/app-source/android/release-v-1-6-5',
            'releases/v1/app-source/android/release-v-1-6-4',
            'releases/v1/app-source/android/release-v-1-6-3',
            'releases/v1/app-source/android/release-v-1-6-2',
            'releases/v1/app-source/android/release-v-1-6-1',
            'releases/v1/app-source/android/release-v-1-6-0',
            'releases/v1/app-source/android/release-v-1-5-1',
            'releases/v1/app-source/android/release-v-1-5-0',
            'releases/v1/app-source/android/release-v-1-4-2',
            'releases/v1/app-source/android/release-v-1-4-1',
            'releases/v1/app-source/android/release-v-1-4-0',
            'releases/v1/app-source/android/release-v-1-3-2',
            'releases/v1/app-source/android/release-v-1-3-1',
            'releases/v1/app-source/android/release-v-1-3-0',
            'releases/v1/app-source/android/release-v-1-2-0',
            'releases/v1/app-source/android/release-v-1-1-0',
            'releases/v1/app-source/android/release-v-1-0-0',
          ],
        },
        {
          type: 'category',
          label: 'iOS',
          link: {
            type: 'generated-index',
            title: 'iOS App Source 릴리즈노트',
            image: '/img/docs/releases/release_note_ios.png',
            slug: 'releases/v1/app-source/ios',
          },
          items: [
            'releases/v1/app-source/ios/intro',
            'releases/v1/app-source/ios/release-v-1-8-4',
            'releases/v1/app-source/ios/release-v-1-8-3',
            'releases/v1/app-source/ios/release-v-1-8-2',
            'releases/v1/app-source/ios/release-v-1-8-1',
            'releases/v1/app-source/ios/release-v-1-8-0',
            'releases/v1/app-source/ios/release-v-1-7-1',
            'releases/v1/app-source/ios/release-v-1-7-0',
            'releases/v1/app-source/ios/release-v-1-6-12',
            'releases/v1/app-source/ios/release-v-1-6-11',
            'releases/v1/app-source/ios/release-v-1-6-10',
            'releases/v1/app-source/ios/release-v-1-6-9',
            'releases/v1/app-source/ios/release-v-1-6-8',
            'releases/v1/app-source/ios/release-v-1-6-7',
            'releases/v1/app-source/ios/release-v-1-6-6',
            'releases/v1/app-source/ios/release-v-1-6-5',
            'releases/v1/app-source/ios/release-v-1-6-4',
            'releases/v1/app-source/ios/release-v-1-6-3',
            'releases/v1/app-source/ios/release-v-1-6-2',
            'releases/v1/app-source/ios/release-v-1-6-1',
            'releases/v1/app-source/ios/release-v-1-6-0',
            'releases/v1/app-source/ios/release-v-1-5-1',
            'releases/v1/app-source/ios/release-v-1-5-0',
            'releases/v1/app-source/ios/release-v-1-4-2',
            'releases/v1/app-source/ios/release-v-1-4-1',
            'releases/v1/app-source/ios/release-v-1-4-0',
            'releases/v1/app-source/ios/release-v-1-3-1',
            'releases/v1/app-source/ios/release-v-1-3-0',
            'releases/v1/app-source/ios/release-v-1-2-0',
            'releases/v1/app-source/ios/release-v-1-1-0',
            'releases/v1/app-source/ios/release-v-1-0-0',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
